### ISSUE TITLE
Pipedrive teams endpoint does not work correctly

### ISSUE THREAD

**Issue by sauravganguli** [dlt-hub/verified-sources#363]
**Source name**
Pipedrive

**Describe the bug**
Pipedrive has an endpoint for teams data called Legacy Teams (https://developers.pipedrive.com/docs/api/v1/LegacyTeams)
However, this resource does not work correctly in the dlt pipedrive pipeline. Upon loading this data to BigQuery, we get all fields from all the different endpoints in pipedrive but not the fields for teams endpoint.

**To Reproduce**
Add Legacy teams resource to pipedrive pipeline
```
load_info = pipeline.run(
        pipedrive_source().with_resources(
            "legacyTeams"
        )
    )
```

Additionally define resource in the `ENTITY_MAPPINGS` and `RECENTS_ENTITIES`
`ENTITY_MAPPINGS = ['legacyTeam', None, None)]`
`RECENTS_ENTITIES = {'legacyTeam': "legacyTeams'}`

Now run the pipedrive pipeline

**Expected behavior**
It should load relevant fields from the teams endpoint. A sample load looks like this:
```
"data": [
        {
            "id": 1,
            "name": "Team - DE",
            "description": "",
            "manager_id": 183085,
            "active_flag": 1,
            "deleted_flag": 0,
            "add_time": "2020-01-27 09:13:36",
            "created_by_user_id": 3541770,
            "users": [
                121177,
                145990,
                175703
            ]
        },
```

**Stack traces and other evidence**
See attached json file for schema of the legacy_teams table loaded by dlt
[schema_legacy_teams.json](https://github.com/dlt-hub/verified-sources/files/14334728/schema_legacy_teams.json)

**Running environment**
 - OS: MacOs
 - `dlt` Version: 0.4.2
 - Orchestrator: Google Composer

**Comment by VioletM** [comment]
Hey, as we discussed in [slack thread](https://dlthub-community.slack.com/archives/C04DQA7JJN6/p1709199580443989), the solution here -- is to add a new resource for `legacyTeams` endpoint.

Since this endpoint is currently deprecated, we won't support it in the verified source repo, but you can add it in your code!

You would need to create a standalone resource and use [get_pages](https://github.com/dlt-hub/verified-sources/blob/master/sources/pipedrive/helpers/pages.py#L21) function inside directly. Similar to [leads](https://github.com/dlt-hub/verified-sources/blob/master/sources/pipedrive/__init__.py#L176) resource, but probably with no parameters. Roughly something like:
```
@dlt.resource(primary_key="id", write_disposition="merge")
def teams(
    pipedrive_api_key: str = dlt.secrets.value,
    ),
) -> Iterator[TDataPage]:
    """Resource to incrementally load pipedrive teams by update_time"""
    yield from get_pages(
        "legacyTeams",
        pipedrive_api_key
    )
```
[This link](https://dlthub.com/docs/general-usage/resource#declare-a-standalone-resource) can help with standalone resource.

The problem with adding `legacyTeam` in `settings.py` is that the current pipedrive source is taking all the data from the [recents](https://developers.pipedrive.com/docs/api/v1/Recents#getRecents) endpoint and it doesn't support the `legacyTeams` entity, but only supports

```
activity, activityType, deal, file, filter, note, person, organization, pipeline, product, stage, user
```
